[package]
name = "search"
version = "0.1.0"
edition = "2021"

[lib]
name = "search"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.15.1", features = ["extension-module"] }
rand = "0.9.0"
