from typing import Dict, List, Set

class StrMatch:
    def __init__(self, patterns: List[str]) -> None: ...
    def search_substr(self, text: str) -> Set[str]: ...
    def search_substr_count(self, text: str) -> Dict[str, int]: ...
