name: Default

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  test-coverage:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.6.8

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('pyproject.toml', 'poetry.lock') }}  # Cache based on pyproject.toml and poetry.lock
          restore-keys: |
            ${{ runner.os }}-python

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run Tests and Collect Coverage
        run: |
          poetry run python -m pytest --cov=. --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
